export enum ErrorMessagesEnum {
  INPUT_ERROR = "inputError",
  NAME_IS_REQUIRED = "nameIsRequired",
  PHONE_IS_REQUIRED = "phoneIsRequired",
  EMAIL_IS_REQUIRED = "emailIsRequired",
  MESSAGE_IS_REQUIRED = "messageIsRequired",
  DOB_IS_REQUIRED = "dobIsRequired",
  GENDER_IS_REQUIRED = "genderIsRequired",
  NAME_PATTERN = "namePattern",
  PHONE_PATTERN = "phonePattern",
  EMAIL_PATTERN = "emailPattern",
  EMAIL_IS_INVALID = "emailIsInvalid",
  MAX_LENGTH = "maxLength",
  MAX_LENGTH_MESSAGE = "maxLengthMessage",
  PHONE_IS_TOO_SHORT = "phoneIsTooShort",
  FIRST_NAME_IS_REQUIRED = "firstNameIsRequired",
  LAST_NAME_IS_REQUIRED = "lastNameIsRequired",
  CITY_IS_REQUIRED = "cityIsRequired",
  STATE_IS_REQUIRED = "stateIsRequired",
  COUNTRY_IS_REQUIRED = "countryIsRequired"
}
